### ISSUE TITLE
Video speedup with high refresh rate

### ISSUE THREAD

**Issue by grimmthetallest** [benkonz/gameboy_emulator#35] opened 2020-11-21 03:59 UTC
Environment: Windows 10, Chrome 86

Repro: Built WASM with cargo web deploy, opened Chrome to HTML page and payload. Monitor on 60Hz refresh runs as expected. Monitor on 165Hz refresh rate causes AV desync as the video is sped up several times and the audio backs up/buffers. Tabbing out will cause the audio to continue to run until it has finished catching up to the paused emulation and then the process will repeat on tab in.

**Comment by benkonz** [comment] 2020-11-23 03:10
Interesting! Nice find, I'll take a look at this @grimmthetallest !

**Comment by benkonz** [comment] 2020-11-24 02:11
@grimmthetallest Can you take a look at https://benkonz.github.io/assets/sync_issue/? It's kind of a hacky way to fix the emulation speed, but it seemed like the easiest way to force a 60FPS timer. 

The issue is that `request_animation_frame` calls at the monitors refresh rate.

**Comment by grimmthetallest** [comment] 2020-11-24 03:06
@benkonz It may be a hacky way to fix it, but it does solve the speedup on my monitor.

**Comment by benkonz** [comment] 2020-11-26 01:53
@grimmthetallest Merged the patch and re-deployed to https://benkonz.github.io/assets/emulator/, let me know if you find any more issues!

**Closed** 2020-11-26 01:53 UTC
